version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

  message:
    build: .
    working_dir: /internal__messager
    env_file:
      - .env
    command: uvicorn app:app
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    working_dir: /internal__worker
    env_file:
      - .env
    command: uvicorn app:app
    depends_on:
      rabbitmq:
        condition: service_healthy

  main:
    build: .
    working_dir: /external__main

    ports:
      - 8000:8000
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
